import os
import django
from django.db import connection

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'agritech.settings')
django.setup()

with connection.cursor() as cursor:
    cursor.execute(
        "SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='accounts_user')"
    )
    accounts_user_exists = cursor.fetchone()[0]

    if not accounts_user_exists:
        print('Creating accounts_user table...')
        cursor.execute("""
            CREATE TABLE accounts_user (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                password varchar(128) NOT NULL,
                last_login timestamp with time zone NULL,
                is_superuser boolean NOT NULL,
                username varchar(150) NOT NULL UNIQUE,
                first_name varchar(150) NOT NULL,
                last_name varchar(150) NOT NULL,
                is_staff boolean NOT NULL,
                is_active boolean NOT NULL,
                date_joined timestamp with time zone NOT NULL,
                email varchar(254) NOT NULL,
                role varchar(30) NOT NULL,
                phone varchar(20) NULL,
                address text NULL,
                city varchar(100) NULL,
                state varchar(100) NULL,
                pincode varchar(12) NULL
            )
        """)

    cursor.execute(
        "SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='accounts_user_groups')"
    )
    if not cursor.fetchone()[0]:
        print('Creating accounts_user_groups table...')
        cursor.execute("""
            CREATE TABLE accounts_user_groups (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                user_id bigint NOT NULL,
                group_id integer NOT NULL
            )
        """)

    cursor.execute(
        "SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='accounts_user_user_permissions')"
    )
    if not cursor.fetchone()[0]:
        print('Creating accounts_user_user_permissions table...')
        cursor.execute("""
            CREATE TABLE accounts_user_user_permissions (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                user_id bigint NOT NULL,
                permission_id integer NOT NULL
            )
        """)

    print('Dropping stale accounts_user email uniqueness constraint if present...')
    cursor.execute("ALTER TABLE accounts_user DROP CONSTRAINT IF EXISTS accounts_user_email_key")

    print('Populating missing accounts_user rows from auth_user...')
    cursor.execute("""
        INSERT INTO accounts_user (
            id, password, last_login, is_superuser, username, first_name,
            last_name, is_staff, is_active, date_joined, email, role
        )
        OVERRIDING SYSTEM VALUE
        SELECT
            au.id,
            au.password,
            au.last_login,
            au.is_superuser,
            au.username,
            au.first_name,
            au.last_name,
            au.is_staff,
            au.is_active,
            au.date_joined,
            au.email,
            COALESCE(up.user_type, 'customer')
        FROM auth_user au
        LEFT JOIN accounts_userprofile up ON up.user_id = au.id
        WHERE NOT EXISTS(SELECT 1 FROM accounts_user au2 WHERE au2.id = au.id)
    """)

    print('Populating accounts_user_groups from auth_user_groups...')
    cursor.execute("""
        INSERT INTO accounts_user_groups (user_id, group_id)
        SELECT ug.user_id, ug.group_id
        FROM auth_user_groups ug
        WHERE NOT EXISTS(
            SELECT 1 FROM accounts_user_groups aug
            WHERE aug.user_id = ug.user_id AND aug.group_id = ug.group_id
        )
    """)

    print('Populating accounts_user_user_permissions from auth_user_user_permissions...')
    cursor.execute("""
        INSERT INTO accounts_user_user_permissions (user_id, permission_id)
        SELECT up.user_id, up.permission_id
        FROM auth_user_user_permissions up
        WHERE NOT EXISTS(
            SELECT 1 FROM accounts_user_user_permissions aup
            WHERE aup.user_id = up.user_id AND aup.permission_id = up.permission_id
        )
    """)

    print('Creating accounts_user indexes...')
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS accounts_user_username_6088629e_like ON accounts_user (username varchar_pattern_ops)"
    )
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS accounts_user_email_b2644a56_like ON accounts_user (email varchar_pattern_ops)"
    )

    print('Creating accounts_user_groups constraints and indexes...')
    cursor.execute(
        "ALTER TABLE accounts_user_groups ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id)"
    )
    cursor.execute(
        "ALTER TABLE accounts_user_groups ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED"
    )
    cursor.execute(
        "ALTER TABLE accounts_user_groups ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES auth_group (id) DEFERRABLE INITIALLY DEFERRED"
    )
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS accounts_user_groups_user_id_52b62117 ON accounts_user_groups (user_id)"
    )
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS accounts_user_groups_group_id_bd11a704 ON accounts_user_groups (group_id)"
    )

    print('Creating accounts_user_user_permissions constraints and indexes...')
    cursor.execute(
        "ALTER TABLE accounts_user_user_permissions ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id)"
    )
    cursor.execute(
        "ALTER TABLE accounts_user_user_permissions ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED"
    )
    cursor.execute(
        "ALTER TABLE accounts_user_user_permissions ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES auth_permission (id) DEFERRABLE INITIALLY DEFERRED"
    )
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS accounts_user_user_permissions_user_id_e4f0a161 ON accounts_user_user_permissions (user_id)"
    )
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS accounts_user_user_permissions_permission_id_113bb443 ON accounts_user_user_permissions (permission_id)"
    )

    print('Repairing accounts_userprofile foreign key if necessary...')
    cursor.execute(
        "SELECT tc.constraint_name, ccu.table_name "
        "FROM information_schema.table_constraints tc "
        "JOIN information_schema.key_column_usage kcu ON tc.constraint_name=kcu.constraint_name "
        "JOIN information_schema.constraint_column_usage ccu ON ccu.constraint_name=tc.constraint_name "
        "WHERE tc.table_name='accounts_userprofile' AND tc.constraint_type='FOREIGN KEY' AND kcu.column_name='user_id'"
    )
    fk_rows = cursor.fetchall()
    auth_fk = None
    for constraint_name, referenced_table in fk_rows:
        if referenced_table == 'auth_user':
            auth_fk = constraint_name
            break

    if auth_fk:
        print(f'Dropping old auth_user FK constraint {auth_fk}')
        cursor.execute(f'ALTER TABLE accounts_userprofile DROP CONSTRAINT "{auth_fk}"')

    print('Validating user_id values in accounts_userprofile...')
    cursor.execute(
        "SELECT user_id FROM accounts_userprofile WHERE user_id NOT IN (SELECT id FROM accounts_user) LIMIT 10"
    )
    missing = cursor.fetchall()
    if missing:
        print('Missing accounts_user IDs for userprofile:', missing)
        raise SystemExit(1)

    cursor.execute(
        "ALTER TABLE accounts_userprofile ADD CONSTRAINT accounts_userprofile_user_id_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED"
    )

print('accounts_user repair complete.')
