# Generated by Django 6.0.6 on 2026-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_video',
            field=models.FileField(blank=True, help_text='Upload a background video (mp4). If present, video will be shown instead of image.', null=True, upload_to='backgrounds/'),
        ),
    ]
