# Generated by Django 6.0.6 on 2026-06-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_background_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_background_video',
            field=models.BooleanField(default=False, help_text='Enable background video display (if video is uploaded)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_watermark',
            field=models.BooleanField(default=False, help_text='Enable watermark display on the website'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='watermark_image',
            field=models.ImageField(blank=True, help_text='Upload an image as watermark (PNG recommended for transparency). Size: 200x200px or smaller.', null=True, upload_to='watermarks/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='watermark_opacity',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='Opacity of watermark (0.0 to 1.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='watermark_position',
            field=models.CharField(choices=[('top-left', 'Top Left'), ('top-center', 'Top Center'), ('top-right', 'Top Right'), ('middle-left', 'Middle Left'), ('center', 'Center'), ('middle-right', 'Middle Right'), ('bottom-left', 'Bottom Left'), ('bottom-center', 'Bottom Center'), ('bottom-right', 'Bottom Right')], default='bottom-right', help_text='Position of the watermark on the page', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='watermark_video',
            field=models.FileField(blank=True, help_text='Upload a video as watermark (mp4, webm). If both image and video are present, video takes priority.', null=True, upload_to='watermarks/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='background_image',
            field=models.ImageField(help_text='Upload a background image. Recommended size: 1920x1080px', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='background_video',
            field=models.FileField(blank=True, help_text='Upload a background video (mp4, webm). If present, video will be shown instead of image.', null=True, upload_to='backgrounds/'),
        ),
    ]
