# Generated by Django 6.0.6 on 2026-06-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Upload a background image. Recommended size: 1920x1080px', null=True, upload_to='backgrounds/'),
        ),
    ]
