# Generated by Django 6.0.6 on 2026-06-15 09:22

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesettings_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_watermark',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='watermark_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='watermark_opacity',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='watermark_position',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='watermark_video',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='background_video',
            field=models.FileField(blank=True, help_text='Upload a background video (mp4, webm) to display on the homepage.', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_background_video',
            field=models.BooleanField(default=False, help_text='Enable background video display on the homepage.'),
        ),
    ]
