# Generated by Django 6.0.6 on 2026-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_create_default_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_in_navbar',
            field=models.BooleanField(default=True),
        ),
    ]
