# Generated by Django 6.0.6 on 2026-06-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('gardener', 'Gardener'), ('doctor', 'Doctor'), ('seller', 'Seller'), ('nursery_owner', 'Nursery Owner')], default='customer', max_length=20),
        ),
    ]
