# Generated by Django 6.0.6 on 2026-06-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user_type_nullable'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='user_type',
                    field=models.CharField(blank=True, max_length=30, null=True, verbose_name='user type'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee'), ('customer', 'Customer'), ('doctor', 'Doctor'), ('gardener', 'Gardener'), ('seller', 'Seller'), ('nursery_owner', 'Nursery Owner'), ('delivery_partner', 'Delivery Partner'), ('consultant', 'Consultant'), ('vendor', 'Vendor')], default='customer', help_text='Primary role assigned to the user.', max_length=30, verbose_name='role'),
        ),
    ]
