# Generated by Django 6.0.6 on 2026-06-20 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_user_type_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='usage limit')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='used count')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_registration_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin registration code',
                'verbose_name_plural': 'admin registration codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
