# Generated by Django 6.0.6 on 2026-06-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_plant_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='plant_image',
            new_name='image',
        ),
    ]
