# Generated by Django 6.0.6 on 2026-06-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_rename_plant_image_consultation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='disease_description',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='plant_name',
        ),
    ]
