# Generated by Django 6.0.6 on 2026-06-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_remove_consultation_disease_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='confirmation_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='confirmation_method',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('call', 'Phone Call')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
