# Generated by Django 6.0.6 on 2026-06-16 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_notificationlog'),
        ('doctors', '0004_doctor_fees'),
        ('services', '0005_add_doctors_gardeners_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='services.service'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
