# Generated by Django 6.0.6 on 2026-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_consultation_service_alter_consultation_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='animal_name',
            field=models.CharField(blank=True, help_text='Name of the pet/animal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='animal_type',
            field=models.CharField(blank=True, help_text='Type of pet/animal (e.g., Dog, Cat, Goat, Cow)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='area_size',
            field=models.CharField(blank=True, help_text='Area size for gardening services (e.g., 1000 sqft)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of issue or service needed', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration for contract gardening (e.g., 3 months, 1 year)', max_length=100, null=True),
        ),
    ]
