# Generated by Django 6.0.6 on 2026-06-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_consultation_animal_name_consultation_animal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='consultation',
            name='reports',
            field=models.FileField(blank=True, null=True, upload_to='consultation_reports/'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
