# Generated by Django 6.0.6 on 2026-06-08 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardeners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Plant Care', 'Plant Care'), ('Garden Setup', 'Garden Setup'), ('Lawn Maintenance', 'Lawn Maintenance'), ('Landscaping', 'Landscaping'), ('Pot Replacement', 'Pot Replacement')], max_length=100)),
                ('booking_date', models.DateField()),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gardener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardeners.gardener')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
