# Generated by Django 6.0.6 on 2026-06-11 06:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardeners', '0002_gardenerbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardener',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
