# Generated by Django 6.0.6 on 2026-06-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('image', models.ImageField(upload_to='doctors/')),
                ('bio', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
