# Generated by Django 6.0.6 on 2026-06-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
